name 'patch_cookbook'
maintainer 'Manjunath Reddy'
maintainer_email 'manjunath.reddy@progress.com'
license 'Apache-2.0'
description 'Sample Patch Management Cookbook'
version '0.1.1'

depends 'wsus-client'
depends 'wsus-server'
depends 'yum'